// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title  ALTBankVault
 * @author Artificial Ledger Technology
 * @notice ERC-4626 tokenized deposit vault for the ALT-Ledger-Bank DeFi protocol.
 *         Users deposit ERC-20 assets and receive `vALT` vault shares that appreciate
 *         as yield is generated by the protocol.
 *
 * @dev    Key Security Design:
 *
 *         1. FIRST-DEPOSITOR INFLATION ATTACK MITIGATION
 *            1,000 "dead shares" are minted to address(0xdead) at construction.
 *            This ensures the share-to-asset ratio can never be manipulated by
 *            front-running the first deposit with a massive direct token transfer.
 *
 *         2. PAUSE SEMANTICS
 *            `deposit()` and `mint()` are gated by `whenNotPaused`.
 *            `withdraw()` and `redeem()` are NEVER paused — users can always exit.
 *
 *         3. EMERGENCY WITHDRAWAL
 *            Available even during pause. Charges a 1% penalty (100 bps) sent
 *            to the protocol treasury. This incentivizes normal withdrawal when
 *            the protocol is healthy but guarantees an exit path.
 *
 *         4. YIELD INJECTION
 *            `depositYield()` allows OPERATOR_ROLE to deposit protocol earnings
 *            into the vault, increasing totalAssets without minting new shares.
 *            This transparently raises the share price for all holders.
 *
 *         5. REENTRANCY GUARD
 *            All external state-mutating functions are protected by OpenZeppelin's
 *            ReentrancyGuard to prevent cross-function reentrancy attacks.
 */
contract ALTBankVault is ERC4626, ReentrancyGuard, Pausable, AccessControl {
    using SafeERC20 for IERC20;

    // ─── Roles ────────────────────────────────────────────────────────────────

    /// @notice Can deposit yield, pause/unpause the vault
    bytes32 public constant OPERATOR_ROLE = keccak256("OPERATOR_ROLE");

    // ─── Constants ─────────────────────────────────────────────────────────────

    /// @notice Emergency withdrawal penalty in basis points (1% = 100 bps)
    uint256 public constant EMERGENCY_PENALTY_BPS = 100;

    /// @notice Basis points denominator
    uint256 public constant BPS_DENOMINATOR = 10_000;

    /// @notice Dead shares minted at construction to prevent inflation attack
    uint256 public constant DEAD_SHARES = 1_000;

    /// @notice Dead share recipient — a known burn address
    address public constant DEAD_ADDRESS = address(0xdead);

    // ─── State Variables ──────────────────────────────────────────────────────

    /// @notice Treasury address that receives emergency withdrawal penalties
    address public treasury;

    /// @notice Total yield deposited over the lifetime of the vault (for analytics)
    uint256 public totalYieldDeposited;

    // ─── Custom Errors ─────────────────────────────────────────────────────────

    error ZeroAddress();
    error ZeroAmount();
    error InsufficientShares(uint256 requested, uint256 available);

    // ─── Events ───────────────────────────────────────────────────────────────

    event YieldDeposited(uint256 amount, uint256 newTotalAssets, uint256 timestamp);
    event EmergencyWithdrawal(address indexed user, uint256 shares, uint256 assetsReceived, uint256 penaltyAmount);
    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);

    // ─── Constructor ───────────────────────────────────────────────────────────

    /**
     * @param _asset     The underlying ERC-20 asset deposited into the vault (e.g., ALTBankToken)
     * @param _admin     Address receiving DEFAULT_ADMIN_ROLE and initial OPERATOR_ROLE
     * @param _treasury  Address where emergency withdrawal penalties are sent
     */
    constructor(IERC20 _asset, address _admin, address _treasury) ERC4626(_asset) ERC20("ALT Vault Share", "vALT") {
        if (_admin == address(0)) revert ZeroAddress();
        if (_treasury == address(0)) revert ZeroAddress();

        treasury = _treasury;

        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(OPERATOR_ROLE, _admin);

        // Mint dead shares to prevent first-depositor inflation attack
        // These shares are permanently locked and make the attack economically infeasible
        _mint(DEAD_ADDRESS, DEAD_SHARES);
    }

    // ─── ERC-4626 Overrides (Pause Enforcement) ───────────────────────────────

    /**
     * @notice Deposit assets and receive vault shares. BLOCKED when paused.
     */
    function deposit(uint256 assets, address receiver) public override nonReentrant whenNotPaused returns (uint256) {
        if (assets == 0) revert ZeroAmount();
        return super.deposit(assets, receiver);
    }

    /**
     * @notice Mint exact shares by depositing equivalent assets. BLOCKED when paused.
     */
    function mint(uint256 shares, address receiver) public override nonReentrant whenNotPaused returns (uint256) {
        if (shares == 0) revert ZeroAmount();
        return super.mint(shares, receiver);
    }

    /**
     * @notice Withdraw assets by burning shares. NEVER blocked by pause.
     */
    function withdraw(uint256 assets, address receiver, address owner) public override nonReentrant returns (uint256) {
        return super.withdraw(assets, receiver, owner);
    }

    /**
     * @notice Redeem shares for underlying assets. NEVER blocked by pause.
     */
    function redeem(uint256 shares, address receiver, address owner) public override nonReentrant returns (uint256) {
        return super.redeem(shares, receiver, owner);
    }

    // ─── Emergency Withdrawal ──────────────────────────────────────────────────

    /**
     * @notice Emergency exit — available even when paused.
     *         Burns the caller's shares and returns assets minus a 1% penalty.
     *         The penalty goes to the protocol treasury.
     *
     * @dev    The penalty ensures protocol revenue even during emergencies while
     *         guaranteeing users can always exit. Penalty is calculated on the
     *         gross asset value of the shares, not on the net amount.
     *
     * @param  shares  Number of vault shares to redeem.
     */
    function emergencyWithdraw(uint256 shares) external nonReentrant {
        if (shares == 0) revert ZeroAmount();
        uint256 userBalance = balanceOf(msg.sender);
        if (shares > userBalance) revert InsufficientShares(shares, userBalance);

        // Calculate gross assets, then split into penalty + user payout
        uint256 grossAssets = convertToAssets(shares);
        uint256 penalty = (grossAssets * EMERGENCY_PENALTY_BPS) / BPS_DENOMINATOR;
        uint256 netAssets = grossAssets - penalty;

        // Burn shares first (checks-effects-interactions)
        _burn(msg.sender, shares);

        // Transfer penalty to treasury, remainder to user
        IERC20 underlying = IERC20(asset());
        underlying.safeTransfer(treasury, penalty);
        underlying.safeTransfer(msg.sender, netAssets);

        emit EmergencyWithdrawal(msg.sender, shares, netAssets, penalty);
    }

    // ─── Yield Injection ───────────────────────────────────────────────────────

    /**
     * @notice OPERATOR deposits protocol yield into the vault.
     *         Increases totalAssets() without minting new shares, thereby
     *         raising the share price for all existing depositors.
     *
     * @dev    Uses transferFrom — caller must have approved this vault for `amount`.
     *
     * @param  amount  Amount of underlying asset to deposit as yield.
     */
    function depositYield(uint256 amount) external onlyRole(OPERATOR_ROLE) nonReentrant {
        if (amount == 0) revert ZeroAmount();

        IERC20(asset()).safeTransferFrom(msg.sender, address(this), amount);
        totalYieldDeposited += amount;

        emit YieldDeposited(amount, totalAssets(), block.timestamp);
    }

    // ─── Admin Functions ───────────────────────────────────────────────────────

    /**
     * @notice Update the treasury address where penalties are collected.
     * @param  newTreasury  The new treasury address. Cannot be zero.
     */
    function setTreasury(address newTreasury) external onlyRole(DEFAULT_ADMIN_ROLE) {
        if (newTreasury == address(0)) revert ZeroAddress();
        address old = treasury;
        treasury = newTreasury;
        emit TreasuryUpdated(old, newTreasury);
    }

    /**
     * @notice Pause the vault — blocks deposit() and mint(). Withdrawals are never affected.
     */
    function pause() external onlyRole(OPERATOR_ROLE) {
        _pause();
    }

    /**
     * @notice Unpause the vault — re-enables deposit() and mint().
     */
    function unpause() external onlyRole(OPERATOR_ROLE) {
        _unpause();
    }
}
